'use strict';

const { Sequelize, db } = require('../db/config.js');

// In Sequelize, db.define() create table
// Model name is singular, Sequelize use plurial wh. create table

// Field auto-generated by sequelize (pg?)
// createdAt, updatedAt
const User = db.define(
    'User',
    {
        id: {
            type: Sequelize.UUID,
            primaryKey: true,
            allowNull: false,
            unique: true,
            defaultValue: Sequelize.UUIDV4,
        },
        email: {
            type: Sequelize.STRING,
            unique: true,
            allowNull: false,
        },
        password: {
            type: Sequelize.STRING,
            allowNull: false,
        },
        salt: {
            type: Sequelize.STRING,
            allowNull: false,
        },
        blocked: {
            type: Sequelize.BOOLEAN,
            defaultValue: false,
        },
        count: {
            type: Sequelize.INTEGER,
            defaultValue: 0,
        },
    },
    {}
);

async function dropUserTable() {
    try {
        await User.drop();
        console.log('User table dropped!');
        await User.sync();
    } catch (error) {
        console.error('Unable to drop user table:', error);
    }
}

// Drop table (only for development...)
if (process.env['NODE_ENV'] === 'development') {
    dropUserTable();
} else {
    // This creates the table if it doesn't exist (and does nothing if it already exists)
    User.sync();
}

// the defined model is the class itself
console.log(User === db.models.User); // true

module.exports = User;
